# Generated by Django 4.2.3 on 2023-07-24 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 7, 25, 1, 37, 10, 249973))),
            ],
        ),
    ]
