# Generated by Django 4.2.3 on 2023-07-24 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 2, 39, 12, 40513)),
        ),
    ]
